language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: ng+BJMaFhEqzYepBnyoQ63wkwk+4ve1RybR7QZXSn+n0Y4VFWqR5guWwqNh69SFOiKs+mYMcWMJ6nA+7Wf/ceeuUcyYZV1pEwj4IxYYZClRUIgRiwebC2OkUK3zBFL2hjW5nQ7qPvakxxhA5HJ18BbBEYms9wTwtniOXHm5fd6WsokMVGEEAO/pgyNxosIL/L7t8W58U1bCnGg0VcEZnfZgBfPOgsVz8VjmJpLNEAhigbEMsDV0M2fxyiuW47Cpq4xGcU2vgoOcLcCg7Zeq9k0M8cLivhLGJu3MuUtH3vlH02bXgnMSD6rgDvlZ4vrZ74aXe8MvCSuUuwPOc81iIQasQxu3SwFO7T0+hs/mYXwCB84lszsZfvkhDyDgNICM8gQQ2mMQEsswsfZDJSLkGwuSTfLmmwAUUB+kS/XWh8jqlbitF5RQyXhP9W+rs8kfmWnr+ff/zGg5N6YedqV1x23kEurekceApCPVoTi8JBmixRwBmfU8OLFIltCl8ckVljbxYcz914NiqLGPmEqlVW7qnsx5HwgPsXuJVkHxnRVFgpJtO76puJTteGSbyYaw/jmaVdgRKKeM5CcuLXJvnyRyGh6K01k5lRelem5XlXELztxPKCXa3+IpyYMxWwk88xBp2tPjLAd1SNY4im/K7deJ44IT2OMZLXJnrx2XmccI=
  app: calvin-hobbes98
