language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
  provider: heroku
  app: calvin-hobbes98
  api_key:
    secure: gLK+ITdEvuRiFuCRgkWYsLAGDKqj9fzX4S0p0bTdd4s/C8iCL4MtWSnh/4LdzTrCi+b2owO5oG61/DnB6vGbL0LSw2d/vsrMQcI8taG9pD31FYFcQfdRJj5Rtch1g+s4VOBDI+6C/l3lu6zA1uYIXc3b6hGVCPHQ2Xesi0dvavt7feUocCH8odoJaikPGuYlYwpH9q1zFDBYy72n6hxKeodVRvmxhArCDV1L0E/Na0eGOvsIFOL//qrIGyWzTTWMbkKWaEAxWUecUZX3Cz/Wpj6uiFqU8gioFrPNALJZwv02aMfpvhD8e8zc8idsgdkeAwIi9A0aXnDYO3OFIvFHmSH4Mb0Bu5mo2XGZ2S2y0tex5FMnML7HPOHjpnXA0YW9uB6tGFdeL1zVqmF9zRx8V0e1JFJhhN5hOk4pP3biHmLhuQXZLIta7hyP2hFO0BewTaVU2nNGp/ZlebRHllpjyaWHSwFmHa99Mcz/+q8kA3ksn+9pvMNgJu3D3RVx0+sx1HY8p7JKZt8fdndvas8i1zNMj14BBEEQjMRj/zvGafczeChfJoFaH2UB9WDG6wCEBwhq75fwVa2M7O/Gt7LRLViGeMQ+iYcbZwQZFkVYeSJ0HfhvH6nA0Q+ff7AjrB0yhKjOBuCZsUcDK8gfX2B/GcZdahMO1qmWv5cDPYyaNsc=
